### ISSUE TITLE
Question on enabling serial console access

### ISSUE THREAD

**Issue by HanpengJ** [ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96#1]
Hi ikwzm,

I have tried your pre-build binaries. They all work fine. But since I am using the Ultra96V2 as an embedded platform without the need of a desktop, I am thinking about building a Ubuntu core rootfs for the Ultra96V2 and using serial console as a way to debug. I would like to ask could you please point me a direct to look into on how I should enable a serial console this device?

Currently, reading through the board's UART port, I can receive everything the u-boot send out. But nothing happened after "Starting kernel". Does it means that there is some kernel configuration or dts I would need to change to make it happen?

Thank you very much!
Sincerely,
Hanpeng

**Comment by ikwzm** [comment]
Thank you for your issue.

Added documentation on how to change the system console. See here for details.

https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96/blob/master/doc/faq/change_system_console.md

**Comment by HanpengJ** [comment]
I have tried the change. It works great!

Thank you for your help!

**Comment by ikwzm** [comment]
I'm glad I could help you.
