### ISSUE TITLE
Improper Power Up Sequence (Ultra96-V2)

### ISSUE THREAD

**Issue by CraigOpie** [ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96#3]
All files and settings are default as downloaded from master.  Boot sequence prints the following to display (repeating):

> power up request for already powered up source wifi
> wilc_sdio mmc1:0001:1: wilc_sdio_cmd53..failed, err(-110)
> wilc_sdio mmc1:0001:1: Failed cmd53, read reg (003b0000)...
> [wilc start]: fail read reg 0x3b0000
> wilc_sdio mmc1:0001:1: wilc_sdio_cmd53..failed, err(-110)
> wilc_sdio mmc1:0001:1: Failed cmd53, read reg (00001000)...
> wilc_sdio mmc1:0001:1: Unsupported chipid: 0

**Comment by ikwzm** [comment]
Thank you for the issue.

Unfortunately, I have never encountered such an event.
Is it a hardware failure?
Does your Ultra96-V2 Wifi work on other systems (eg PetaLinux)?

What happens if I turn off the Ultra96-V2, wait for a while, and then turn it on?

**Comment by CraigOpie** [comment]
It doesn't seem to be hardware failure.  The board is brand new and out of the box today, I used ESD precautions while handling the board, and the ultra96 oob software boots up without any issues.  wlan0 works correctly.  I tried changing the SD cards and have the same indications.  Also, I'm using ubuntu 18.04 to copy the image over to the SD card.

If I turn off the Ultra96-V2, wait for 10 minutes, and then power it back on, I have the same indications.

I tried changing the rootwait to rootdelay to see if the bootloader would continue past the issue but that didn't work either.

**Comment by ikwzm** [comment]
Thank you for the useful information.
However, this is a problem I have never encountered and may not be solved by me.

If you like, could you try the following projects as well? In both cases, the Linux Kernel version is 5.4.0.

 * https://github.com/ikwzm/ZynqMP-FPGA-Linux
 * https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu20.04-Ultra96

**Comment by CraigOpie** [comment]
Thanks.  Issue is not present in: 
- [https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu20.04-Ultra96](https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu20.04-Ultra96)
